# Generated by Django 5.2.1 on 2025-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptionalschedule',
            options={'ordering': ['start_date'], 'verbose_name': 'Horaire exceptionnel', 'verbose_name_plural': 'Horaires exceptionnels'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='exceptionalschedule',
            index=models.Index(fields=['start_date'], name='backoffice__start_d_e8c5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='exceptionalschedule',
            index=models.Index(fields=['type'], name='backoffice__type_fb8a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'time'], name='backoffice__date_bda607_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='backoffice__status_c57ab6_idx'),
        ),
    ]
